name: Build and deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install uv
        run: |
          python3 -m pip install uv

      - name: Get uv cache dir
        id: uv-cache
        run: echo "::set-output name=dir::$(uv cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v4.2.4
        with:
          path: ${{ steps.uv-cache.outputs.dir }}
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: python3 -m uv sync

      - name: Generate HTML using Sphinx
        run: |
          ./venv/bin/python3 -m sphinx-build -M html dl4s_book build

      - name: Publish HTML to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
